package execenv

import (
	"fmt"
	"log/slog"
	"os"
	"regexp"
	"strings"
)

const GoosarRuntimeEMultiAgentEnv = "GOOSAR_RUNTIME_E_MULTI_AGENT"

const (
	goosarMultiAgentBeginMarker = "# BEGIN goosar-managed multi-agent (do not edit; regenerated by daemon)"
	goosarMultiAgentEndMarker   = "# END goosar-managed multi-agent"
)

var multiAgentBlockRe = regexp.MustCompile(
	`(?ms)^` + regexp.QuoteMeta(goosarMultiAgentBeginMarker) +
		`.*?^` + regexp.QuoteMeta(goosarMultiAgentEndMarker) + `\n*`)

var (
	rootFeaturesTableHeaderRe = regexp.MustCompile(`^\s*\[\s*features\s*\]\s*(?:#.*)?$`)

	featuresTableMultiAgentRe = regexp.MustCompile(`^\s*multi_agent\s*=`)

	rootDottedMultiAgentRe = regexp.MustCompile(`^\s*features\s*\.\s*multi_agent\s*=`)
)

func codexMultiAgentEnabled() bool {
	raw := strings.TrimSpace(os.Getenv(GoosarRuntimeEMultiAgentEnv))
	switch strings.ToLower(raw) {
	case "1", "true", "yes", "on":
		return true
	}
	return false
}

func renderGoosarMultiAgentBlock(inFeaturesTable bool) string {
	var b strings.Builder
	b.WriteString(goosarMultiAgentBeginMarker)
	b.WriteString("\n")
	if inFeaturesTable {
		b.WriteString("multi_agent = false\n")
	} else {
		b.WriteString("features.multi_agent = false\n")
	}
	b.WriteString(goosarMultiAgentEndMarker)
	b.WriteString("\n")
	return b.String()
}

func stripUserMultiAgentDirectives(content string) string {
	lines := strings.Split(content, "\n")
	out := make([]string, 0, len(lines))
	currentTable := ""
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if rootFeaturesTableHeaderRe.MatchString(line) {
			currentTable = "[features]"
			out = append(out, line)
			continue
		}
		if strings.HasPrefix(trimmed, "[") {
			currentTable = trimmed
			out = append(out, line)
			continue
		}
		switch currentTable {
		case "":
			if rootDottedMultiAgentRe.MatchString(trimmed) {
				continue
			}
		case "[features]":
			if featuresTableMultiAgentRe.MatchString(trimmed) {
				continue
			}
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}

func hasRootFeaturesTable(content string) bool {
	for _, line := range strings.Split(content, "\n") {
		if rootFeaturesTableHeaderRe.MatchString(line) {
			return true
		}
	}
	return false
}

func injectManagedBlockIntoFeaturesTable(content string) string {
	block := renderGoosarMultiAgentBlock(true)

	blockLines := strings.Split(strings.TrimRight(block, "\n"), "\n")
	lines := strings.Split(content, "\n")
	for i, line := range lines {
		if !rootFeaturesTableHeaderRe.MatchString(line) {
			continue
		}
		out := make([]string, 0, len(lines)+len(blockLines))
		out = append(out, lines[:i+1]...)
		out = append(out, blockLines...)
		out = append(out, lines[i+1:]...)
		return strings.Join(out, "\n")
	}
	return content
}

func ensureCodexMultiAgentConfig(configPath string, logger *slog.Logger) error {
	if codexMultiAgentEnabled() {
		if logger != nil {
			logger.Info("codex multi-agent: leaving Codex native multi-agent untouched per GOOSAR_RUNTIME_E_MULTI_AGENT",
				"config_path", configPath,
			)
		}
		return nil
	}

	data, err := os.ReadFile(configPath)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read config.toml: %w", err)
	}
	existing := string(data)

	existing = multiAgentBlockRe.ReplaceAllString(existing, "")

	existing = stripUserMultiAgentDirectives(existing)

	var updated string
	if hasRootFeaturesTable(existing) {
		updated = injectManagedBlockIntoFeaturesTable(existing)
	} else {
		existing = strings.TrimLeft(existing, "\n")
		block := renderGoosarMultiAgentBlock(false)
		if existing == "" {
			updated = block
		} else {
			updated = block + "\n" + existing
		}
	}

	if updated == string(data) {
		return nil
	}

	if err := os.WriteFile(configPath, []byte(updated), 0o644); err != nil {
		return fmt.Errorf("write config.toml: %w", err)
	}
	return nil
}
