# Shared local development env derivation. Source this after loading .env.

POSTGRES_DB="${POSTGRES_DB:-goosar}"
POSTGRES_USER="${POSTGRES_USER:-goosar}"
POSTGRES_PORT="${POSTGRES_PORT:-5433}"

PORT="${BACKEND_PORT:-${API_PORT:-${SERVER_PORT:-${PORT:-8081}}}}"
FRONTEND_PORT="${FRONTEND_PORT:-3001}"
FRONTEND_ORIGIN="${FRONTEND_ORIGIN:-http://localhost:${FRONTEND_PORT}}"

GOOSAR_APP_URL="${GOOSAR_APP_URL:-${FRONTEND_ORIGIN}}"
GOOSAR_SERVER_URL="${GOOSAR_SERVER_URL:-ws://localhost:${PORT}/ws}"
LOCAL_UPLOAD_BASE_URL="${LOCAL_UPLOAD_BASE_URL:-http://localhost:${PORT}}"
PLAYWRIGHT_BASE_URL="${PLAYWRIGHT_BASE_URL:-${FRONTEND_ORIGIN}}"

export POSTGRES_DB POSTGRES_USER POSTGRES_PORT
export PORT FRONTEND_PORT FRONTEND_ORIGIN
export GOOSAR_APP_URL GOOSAR_SERVER_URL LOCAL_UPLOAD_BASE_URL
export PLAYWRIGHT_BASE_URL
