// Команда genstubs генерирует server2/internal/app/stubs_gen.go: по одному
// router.HandleStub(...) на каждую операцию docs/50-api-contract.yaml.
// Домены "вытесняют" эти заглушки, регистрируя тот же method+path первыми
// через router.Handle (см. internal/httpapi/router.go) — генератор поэтому
// не должен знать, какие операции уже реализованы.
//
// Запуск (из server2/):
//
//	go run ./tools/genstubs -spec ../docs/50-api-contract.yaml -out internal/app/stubs_gen.go
package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"

	"github.com/adanman/goosar/server2/internal/contractspec"
)

func main() {
	spec := flag.String("spec", "../docs/50-api-contract.yaml", "путь к docs/50-api-contract.yaml")
	out := flag.String("out", "internal/app/stubs_gen.go", "куда писать сгенерированный файл")
	flag.Parse()

	ops, err := contractspec.Load(*spec)
	if err != nil {
		fmt.Fprintln(os.Stderr, "genstubs:", err)
		os.Exit(1)
	}

	var b strings.Builder
	b.WriteString("// Code generated by server2/tools/genstubs from docs/50-api-contract.yaml. DO NOT EDIT.\n")
	b.WriteString("//\n")
	fmt.Fprintf(&b, "// Операций в контракте: %d. Перегенерировать:\n", len(ops))
	b.WriteString("//\tcd server2 && go run ./tools/genstubs -spec ../docs/50-api-contract.yaml -out internal/app/stubs_gen.go\n")
	b.WriteString("package app\n\n")
	b.WriteString("import (\n\t\"net/http\"\n\n\t\"github.com/adanman/goosar/server2/internal/httpapi\"\n)\n\n")
	b.WriteString("// RegisterStubs регистрирует 501-заглушку для каждой операции контракта.\n")
	b.WriteString("// router.HandleStub — не router.Handle: маршрут, уже занятый доменом, тихо пропускается.\n")
	b.WriteString("func RegisterStubs(router *httpapi.Router) {\n")
	for _, op := range ops {
		fmt.Fprintf(&b, "\trouter.HandleStub(http.%s, %q, httpapi.WriteNotImplemented) // %s\n",
			httpConst(op.Method), op.Path, op.OperationID)
	}
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		fmt.Fprintln(os.Stderr, "genstubs: gofmt:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "genstubs: запись файла:", err)
		os.Exit(1)
	}
	fmt.Printf("genstubs: сгенерировано %d операций в %s\n", len(ops), *out)
}

func httpConst(method string) string {
	return "Method" + strings.Title(strings.ToLower(method)) //nolint:staticcheck // simple ASCII method names
}
